require("prototypes.item")
require("prototypes.entity")
require("prototypes.recipes.machines")
require("prototypes.recipes.ores")
require("prototypes.recipes.wires")
require("prototypes.ores")
require("prototypes.categories")
