require("prototypes.entity")
require("prototypes.categories")

require("prototypes.recipes.machines")
require("prototypes.recipes.ores")
require("prototypes.recipes.wires")
require("prototypes.recipes.gears")
require("prototypes.recipes.plates")
require("prototypes.recipes.liquids")
require("prototypes.recipes.products")

require("prototypes.items.machines")
require("prototypes.items.ores")
require("prototypes.items.wires")
require("prototypes.items.gears")
require("prototypes.items.plates")
require("prototypes.items.liquids")
require("prototypes.items.products")
